server:
  host: 0.0.0.0
  port: 8080
  mode: release  # debug or release

database:
  # Database type: sqlite3, postgres, sqlserver
  type: sqlite3

  # SQLite configuration
  path: ./data/gitserver.db

  # PostgreSQL configuration (uncomment to use)
  # type: postgres
  # host: localhost
  # port: 5432
  # name: zixiao_git
  # user: postgres
  # password: postgres
  # sslmode: disable  # Options: disable, require, verify-ca, verify-full

  # SQL Server configuration (uncomment to use)
  # type: sqlserver
  # host: localhost
  # port: 1433
  # name: zixiao_git
  # user: sa
  # password: YourPassword123

git:
  repo_path: ./data/repositories
  max_repo_size: 1024  # MB
  max_file_size: 100   # MB
  allowed_types: []    # Empty = allow all

security:
  jwt_secret: CHANGE_ME_IN_PRODUCTION_USE_RANDOM_STRING
  jwt_expiration: 24   # hours
  password_min: 8
  enable_ssh: false
  ssh_port: 2222
